Repository vitekkor/mintKV, pull requests merged in 2024-04, with the labels that each got.

#17 add gradle.yml for ci
  .github/workflows/gradle.yml
Labels: Infrastructure

#19 #6: add raft.proto
  database/src/main/proto/internal/raft.proto
Labels: design

#20 #5: add database_service.proto
  database/src/main/proto/external/database_service.proto
Labels: design

#18 Node yaml config
  .github/workflows/checks.xml
  .github/workflows/gradle.yml
  database/build.gradle.kts
  database/src/main/java/com/mint/db/config/ConfigParser.java
  database/src/main/java/com/mint/db/config/NodeConfig.java
  database/src/main/resources/node-config.yaml
Labels: enhancement, Infrastructure
